plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.0.91'
}
group = 'cat.jiu.core'
version = 'forge-0.0.1'
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

base {
    archivesName = project.name + "-" + project.minecraft_version
}

legacyForge {
    version = project.minecraft_version + '-' + project.forge_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }
    accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')
}
configurations {
    runtimeClasspath.extendsFrom localRuntime
}
obfuscation {
    createRemappingConfiguration(configurations.localRuntime)
}
sourceSets.main.resources { srcDir 'src/generated/resources' }
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
